import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["CLISIS_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("CLISIS_CODER_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CLISIS_CODER_AUTO_HEAP_SNAPSHOT: truthy("CLISIS_CODER_AUTO_HEAP_SNAPSHOT"),
  CLISIS_CODER_GIT_BASH_PATH: process.env["CLISIS_CODER_GIT_BASH_PATH"],
  CLISIS_CODER_CONFIG: process.env["CLISIS_CODER_CONFIG"],
  CLISIS_CODER_CONFIG_CONTENT: process.env["CLISIS_CODER_CONFIG_CONTENT"],
  CLISIS_CODER_DISABLE_AUTOUPDATE: truthy("CLISIS_CODER_DISABLE_AUTOUPDATE"),
  CLISIS_CODER_ALWAYS_NOTIFY_UPDATE: truthy("CLISIS_CODER_ALWAYS_NOTIFY_UPDATE"),
  CLISIS_CODER_DISABLE_PRUNE: truthy("CLISIS_CODER_DISABLE_PRUNE"),
  CLISIS_CODER_DISABLE_TERMINAL_TITLE: truthy("CLISIS_CODER_DISABLE_TERMINAL_TITLE"),
  CLISIS_CODER_SHOW_TTFD: truthy("CLISIS_CODER_SHOW_TTFD"),
  CLISIS_CODER_DISABLE_AUTOCOMPACT: truthy("CLISIS_CODER_DISABLE_AUTOCOMPACT"),
  CLISIS_CODER_DISABLE_MODELS_FETCH: truthy("CLISIS_CODER_DISABLE_MODELS_FETCH"),
  CLISIS_CODER_DISABLE_MOUSE: truthy("CLISIS_CODER_DISABLE_MOUSE"),
  CLISIS_CODER_FAKE_VCS: process.env["CLISIS_CODER_FAKE_VCS"],
  CLISIS_CODER_SERVER_PASSWORD: process.env["CLISIS_CODER_SERVER_PASSWORD"],
  CLISIS_CODER_SERVER_USERNAME: process.env["CLISIS_CODER_SERVER_USERNAME"],

  // Experimental
  CLISIS_CODER_EXPERIMENTAL_FILEWATCHER: Config.boolean("CLISIS_CODER_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CLISIS_CODER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CLISIS_CODER_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CLISIS_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CLISIS_CODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CLISIS_CODER_MODELS_URL: process.env["CLISIS_CODER_MODELS_URL"],
  CLISIS_CODER_MODELS_PATH: process.env["CLISIS_CODER_MODELS_PATH"],
  CLISIS_CODER_DB: process.env["CLISIS_CODER_DB"],

  CLISIS_CODER_WORKSPACE_ID: process.env["CLISIS_CODER_WORKSPACE_ID"],
  CLISIS_CODER_EXPERIMENTAL_WORKSPACES: enabledByExperimental("CLISIS_CODER_EXPERIMENTAL_WORKSPACES"),
  CLISIS_CODER_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("CLISIS_CODER_EXPERIMENTAL_SESSION_SWITCHER"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CLISIS_CODER_DISABLE_PROJECT_CONFIG() {
    return truthy("CLISIS_CODER_DISABLE_PROJECT_CONFIG")
  },
  get CLISIS_CODER_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("CLISIS_CODER_EXPERIMENTAL_REFERENCES")
  },
  get CLISIS_CODER_TUI_CONFIG() {
    return process.env["CLISIS_CODER_TUI_CONFIG"]
  },
  get CLISIS_CODER_CONFIG_DIR() {
    return process.env["CLISIS_CODER_CONFIG_DIR"]
  },
  get CLISIS_CODER_PURE() {
    return truthy("CLISIS_CODER_PURE")
  },
  get CLISIS_CODER_PERMISSION() {
    return process.env["CLISIS_CODER_PERMISSION"]
  },
  get CLISIS_CODER_PLUGIN_META_FILE() {
    return process.env["CLISIS_CODER_PLUGIN_META_FILE"]
  },
  get CLISIS_CODER_CLIENT() {
    return process.env["CLISIS_CODER_CLIENT"] ?? "cli"
  },
}
